import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, FileText } from 'lucide-react';
import { getProduct, getAudit } from '@/lib/db';
import { formatDate } from '@/lib/rating';
import { ingredientBySlug } from '@/data/ingredients';
import { EvidenceExport } from '@/components/evidence-export';
import { EvidencePanel } from '@/components/evidence-panel';
import { CompareButton } from '@/components/collection-button';
import { readable } from '@/lib/normalise';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const product=await getProduct((await params).slug);return {title:product?`${product.brand} ${product.name}`:'Product'};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
  const product=await getProduct((await params).slug);if(!product)notFound();const ingredient=ingredientBySlug(product.ingredient_slug)!;const audit=await getAudit(product.id);
  return <main id="main" className="wrap product-page"><Link className="back-link" href={`/supplements/${ingredient.slug}#brands`}><ArrowLeft size={15}/>{ingredient.name} products</Link><section className="product-detail-heading"><div className={`product-emblem theme-${ingredient.theme}`}><span>{ingredient.symbol}</span><small>{product.form}</small></div><div><Link className="eyebrow" href={`/brands/${product.brand_id}`}>{product.brand}<ArrowUpRight size={14}/></Link><h1>{product.name}</h1><p>{product.form} <span>·</span> NPN {product.npn}</p><CompareButton id={product.id} name={`${product.brand} ${product.name}`}/></div></section>
    <div className="product-detail-grid"><EvidencePanel product={product}/><aside className="product-facts"><span className="eyebrow">THE RECORD AT A GLANCE</span><h2>Product identity.</h2><dl><dt>Canadian product number</dt><dd>{product.npn}</dd><dt>Licence holder</dt><dd>{product.licence_holder}</dd><dt>Original licence issued</dt><dd>{formatDate(product.licence_date)}</dd><dt>Licence status at last check</dt><dd>{product.licence_status==='active'?'Active':'Non-active — review required'}</dd><dt>Last successful record retrieval</dt><dd>{formatDate(product.checked_at)}</dd></dl><p className="meta-text">A product’s licence date is not the brand’s founding date. A licence listing does not confirm current shop availability.</p><a className="button secondary" href={`https://health-products.canada.ca/lnhpd-bdpsnh/info?licence=${product.npn}`} target="_blank" rel="noopener noreferrer">Health Canada record <ArrowUpRight size={15}/></a>{product.manufacturer_url&&<a className="text-link" href={product.manufacturer_url} target="_blank" rel="noopener noreferrer">Manufacturer’s information <ArrowUpRight size={14}/></a>}<Link className="text-link" href={`/supplements/${ingredient.slug}`}>Explore the ingredient →</Link></aside></div>
    <section className="licence-detail"><span className="eyebrow"><FileText size={15}/>FROM THE OFFICIAL LICENCE</span><h2>What is actually recorded?</h2><p className="section-intro">These are licence entries, which may include alternative ingredient sources or wording. Do not add repeated ingredient entries together. Check the physical label for the exact formulation and directions.</p><div className="table-scroll"><table><caption>Medicinal ingredients in NPN {product.npn}</caption><thead><tr><th>Ingredient</th><th>Recorded quantity</th><th>Source material</th></tr></thead><tbody>{!product.medicinal.length&&<tr><td colSpan={3}>No ingredient entries were returned by the official endpoint. Formulation evidence remains unverified; consult the current label and licence monograph.</td></tr>}{product.medicinal.map((m,i)=><tr key={i}><td>{readable(m.ingredient_name)||'Not specified'}</td><td>{readable(m.quantity)} {readable(m.quantity_unit_of_measure)}</td><td>{readable(m.source_material)||'Not specified'}</td></tr>)}</tbody></table></div><details className="text-disclosure"><summary>Authorized purpose wording</summary>{product.purposes.length?product.purposes.map((p,i)=><p key={i}>{p}</p>):<p>No purpose text was returned in the retrieved record.</p>}</details><details className="text-disclosure"><summary>Warnings in the retrieved record</summary>{product.risks.length?product.risks.map((p,i)=><p key={i}>{p}</p>):<p>No warning text was returned by this endpoint. This does not establish that the product has no risks. Read the product’s current label.</p>}</details><details className="text-disclosure"><summary>Names associated with this licence</summary><p>{product.aliases.join(' · ')}</p></details></section>
    <section className="audit-section"><div className="section-heading"><div><span className="eyebrow">A RECORD YOU CAN FOLLOW</span><h2>Review history.</h2></div><EvidenceExport product={product} history={audit}/></div>{audit.map(event=><div className="audit-row" key={event.id}><span className="audit-dot"/><div><strong>{event.action.replaceAll('-',' ')}</strong><p>{event.actor==='seed'?'Initial official-record import':event.actor==='editor'?'Editorial review':event.actor==='source-research'?'Source-backed certification review':'Official-record refresh'}</p></div><time>{formatDate(event.created_at)}</time></div>)}</section>
  </main>;
}
