import { test,expect,type Page } from '@playwright/test';
async function visit(page:Page,path:string){const response=await page.goto(path);await expect(page.getByTestId('app-ready')).toHaveAttribute('data-ready','true');return response;}
test('visual discovery, topic filtering, search, and durable collection',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await visit(page,'/');await expect(page.getByRole('heading',{name:/Your body/})).toBeVisible();await expect(page.locator('.ingredient-card')).toHaveCount(18);
  await page.screenshot({path:'test-results/discover-desktop.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Performance',exact:true}).click();await expect(page.locator('.ingredient-card')).toHaveCount(1);await expect(page.locator('.ingredient-card h3')).toHaveText('Creatine');
  await page.getByRole('button',{name:'All discoveries',exact:true}).click();await page.getByRole('textbox',{name:'Search supplements'}).fill('melatonin');await expect(page.locator('.ingredient-card')).toHaveCount(1);await page.getByRole('button',{name:'Save Melatonin to collection'}).click();await visit(page,'/collection');await expect(page.locator('.ingredient-card')).toHaveCount(1);await page.reload();await expect(page.locator('.ingredient-card h3')).toHaveText('Melatonin');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export collection'}).click();expect((await download).suggestedFilename()).toBe('my-neurotrino-collection.json');await page.getByRole('button',{name:'Remove Melatonin from collection'}).click();await expect(page.getByRole('heading',{name:'Your curiosity goes here.'})).toBeVisible();expect(errors).toEqual([]);
});
test('each guide has sources and actual product records',async({page})=>{
  for(const slug of ['magnesium','vitamin-d','omega-3','creatine','l-theanine','melatonin']){await visit(page,`/supplements/${slug}`);await expect(page.locator('.fact-card')).toHaveCount(3);await expect(page.locator('.source-row').first()).toBeVisible();expect(await page.locator('.product-row').count()).toBeGreaterThan(0);}
});
test('NPN search, comparison limit, shared links, and source export',async({page})=>{
  await visit(page,'/products');await page.getByRole('textbox',{name:'Search products'}).fill('80005079');await expect(page.locator('.product-row')).toHaveCount(1);await expect(page.locator('.product-row')).toContainText('Jamieson');await page.getByRole('textbox',{name:'Search products'}).fill('');
  const buttons=page.locator('.product-row-actions button[aria-pressed=false]');await buttons.nth(0).click();await buttons.nth(0).click();await buttons.nth(0).click();await buttons.nth(0).click();await expect(page.getByRole('status')).toContainText('Compare up to 3 products');await page.locator('.compare-tray').getByRole('link').click();await expect(page.locator('.comparison-table thead th')).toHaveCount(4);await page.reload();await expect(page.locator('.comparison-table thead th')).toHaveCount(4);
  const comparisonDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export comparison'}).click();expect((await comparisonDownload).suggestedFilename()).toBe('neurotrino-comparison.json');await page.getByRole('button',{name:/Remove .* from comparison/}).first().click();await expect(page.locator('.comparison-table thead th')).toHaveCount(3);
  await visit(page,'/products/jamieson-80005079');await expect(page.getByRole('heading',{name:'See what stands behind it.'})).toBeVisible();await expect(page.locator('.evidence-score')).toContainText('30');await page.locator('.evidence-check summary').filter({hasText:'Independent product testing'}).click();await expect(page.getByText('No reviewed evidence has been added for this check.').first()).toBeVisible();const response=await page.request.get('/api/products/80005079/evidence');expect(response.ok()).toBeTruthy();const data=await response.json();expect(data.product.npn).toBe('80005079');expect(data.rating.score).toBe(30);expect(data.history.length).toBeGreaterThan(0);
});
test('editor authentication, validation, audited review, and conflict protection',async({page})=>{
  const url='/api/review/evidence/80005079';const denied=await page.request.post(url,{data:{},headers:{Origin:'http://127.0.0.1:3010'}});expect(denied.status()).toBe(403);
  await visit(page,'/review');await page.getByLabel('Editor key').fill('wrong');await page.getByRole('button',{name:'Open editorial desk'}).click();await expect(page.getByText('That editor key is not valid.')).toBeVisible();await page.getByLabel('Editor key').fill('isolated-e2e-editor-token-not-for-deployment');await page.getByRole('button',{name:'Open editorial desk'}).click();await expect(page.getByRole('heading',{name:'Keep the record honest.'})).toBeVisible();
  await page.getByLabel('Editorial product').selectOption('80005079');await page.getByLabel('Evidence check',{exact:true}).selectOption('testing');await page.getByLabel('What did you establish?').fill('Automated end-to-end test in an isolated database: testing remains unverified.');await page.getByLabel('Source URL',{exact:true}).fill('https://example.org/isolated-e2e-fixture');await page.getByLabel('Source title',{exact:true}).fill('Isolated browser test fixture');await page.getByLabel('Publisher',{exact:true}).fill('Automated test');await page.getByLabel('Exact product, market, batch, and review scope').fill('NPN 80005079; isolated e2e data only. No public test evidence is asserted.');await page.getByLabel(/I reviewed this source/).check();await page.getByRole('button',{name:'Publish evidence review'}).click();await expect(page.getByRole('status')).toContainText('Evidence review saved');
  const response=await page.request.get('/api/products/80005079/evidence');const data=await response.json();expect(data.product.evidence.find((e:{kind:string})=>e.kind==='testing').verdict).toBe('unknown');expect(data.history.some((e:{action:string})=>e.action==='evidence-reviewed')).toBeTruthy();
  const existing=data.product.evidence.find((e:{kind:string})=>e.kind==='testing');const conflict=await page.request.post(url,{headers:{Origin:'http://127.0.0.1:3010'},data:{...existing,revision:existing.revision-1,attested:true}});expect(conflict.status()).toBe(409);
  const researchImport=await page.request.post('/api/review/import',{headers:{Origin:'http://127.0.0.1:3010'},data:{npn:'99999999',ingredient:'bpc-157',attested:true}});expect(researchImport.status()).toBe(400);
  await expect(page.getByLabel('Supplement guide').locator('option[value="bpc-157"]')).toHaveCount(0);
  await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('heading',{name:'The editorial desk.'})).toBeVisible();
});
test('mobile layout, reduced motion, navigation, and missing routes',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await visit(page,'/');await expect(page.locator('.ingredient-card')).toHaveCount(18);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/discover-mobile.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'Open menu'}).click();await page.getByRole('navigation').getByRole('link',{name:'My collection',exact:true}).click();await expect(page.getByRole('heading',{name:'Your collection.',exact:true})).toBeVisible();await visit(page,'/supplements/magnesium');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/guide-mobile.png',fullPage:true,animations:'disabled'});await visit(page,'/sources');await expect(page.getByRole('heading',{name:/Back to the source/})).toBeVisible();await visit(page,'/supplements/not-a-real-ingredient');await expect(page.getByRole('heading',{name:'That discovery isn’t here.'})).toBeVisible();await expect(page.locator('meta[name=robots]').first()).toHaveAttribute('content','noindex');expect((await page.request.get('/api/products/99999999/evidence')).status()).toBe(404);
});
