import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, Sparkles, ArrowDown, BookOpen } from 'lucide-react';
import { ingredientBySlug } from '@/data/ingredients';
import { getProducts } from '@/lib/db';
import { SupplementArt } from '@/components/art';
import { CollectButton } from '@/components/collection-button';
import { ConnectionLab } from '@/components/connection-lab';
import { ingredientPairs } from '@/data/connections';
import { ProductBrowser } from '@/components/product-browser';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const ingredient=ingredientBySlug((await params).slug);return {title:ingredient?.name||'Supplement',description:ingredient?.tidbit};}
export default async function IngredientPage({params}:{params:Promise<{slug:string}>}){
  const ingredient=ingredientBySlug((await params).slug);if(!ingredient)notFound();
  const products=(await getProducts()).filter(p=>p.ingredient_slug===ingredient.slug);
  return <main id="main" className="wrap guide-page"><Link href="/#discover" className="back-link"><ArrowLeft size={15}/>All discoveries</Link><section className="guide-hero"><div className={`guide-art theme-${ingredient.theme}`}><span className="card-number">FIELD NOTE / {ingredient.number}</span><SupplementArt slug={ingredient.slug}/><span className="specimen-symbol">{ingredient.symbol}</span><span className="card-category">{ingredient.category}</span></div><div className="guide-intro"><div className="eyebrow">{ingredient.subtitle}</div><h1>{ingredient.name}<span>.</span></h1>{ingredient.kind === "research" && <div className="research-banner"><strong>Experimental peptide · research only</strong><span>{ingredient.caution}</span></div>}<p className="guide-summary">{ingredient.summary}</p><div className="card-tags">{ingredient.tags.map(t=><span key={t}>{t}</span>)}</div><div className="guide-actions"><CollectButton id={ingredient.slug} name={ingredient.name}/>{products.length > 0 ? <a className="text-link" href="#brands">Explore {products.length} products <ArrowDown size={16}/></a> : <a className="text-link" href="#sources">Explore the sources <ArrowDown size={16}/></a>}</div><p className="meta-text"><BookOpen size={14}/>A field note to learn from. A collection to come back to.</p></div></section>
    <section className="facts-section"><div className="section-heading"><div><span className="eyebrow">THE LITTLE THINGS WORTH KNOWING</span><h2>Three things to take with you.</h2></div><Sparkles size={27}/></div><div className="fact-grid">{ingredient.facts.map((fact,i)=><article className="fact-card" key={fact.title}><span>0{i+1}</span><h3>{fact.title}</h3><p>{fact.body}</p><a href={`#source-${fact.source}`} className="text-link">Follow the source <ArrowUpRight size={14}/></a></article>)}</div><div className="context-grid"><div className="context-card"><span className="eyebrow">WHAT THE EVIDENCE MEANS</span><h3>{ingredient.role}</h3><p>{ingredient.limitation}</p></div><div className="context-card caution"><span className="eyebrow">BEFORE YOU CONSIDER TAKING IT</span><h3>Keep the context.</h3><p>{ingredient.caution}</p></div></div></section>
    {ingredientPairs.some(pair => pair.items.includes(ingredient.slug)) && <ConnectionLab pairId={ingredientPairs.find(pair => pair.items.includes(ingredient.slug))?.id}/>}
    {ingredient.kind !== "research" && <section className="brands-section" id="brands"><div className="section-heading"><div><span className="eyebrow">FROM INGREDIENT TO BOTTLE</span><h2>Now, get to know the products.</h2></div><Link className="text-link" href="/methodology">How we check <ArrowUpRight size={15}/></Link></div><p className="section-intro">Compare evidence for the exact formulation. Brand age and marketing claims do not earn quality points.</p>{products.length ? <ProductBrowser products={products} compact/> : <div className="empty-product-note">This field note is ready to explore. Product records for this ingredient have not yet been imported and reviewed; no brand rating is implied.</div>}</section>}
    <section className="guide-sources" id="sources"><span className="eyebrow">KEEP FOLLOWING YOUR CURIOSITY</span><h2>The sources behind this note.</h2>{ingredient.sources.map((source,i)=><a id={`source-${i}`} href={source.url} key={source.url} target="_blank" rel="noopener noreferrer" className="source-row"><span className="source-number">0{i+1}</span><span><strong>{source.title}</strong><small>{source.publisher}</small></span><ArrowUpRight size={19}/></a>)}</section>
  </main>;
}
