'use client';
import { publicPath } from '@/lib/site';
import { useCollection } from './providers';
import Link from 'next/link';
import { useEvidenceTime } from './providers';
import { useRouter } from 'next/navigation';
import { ArrowRight, X, Layers3 } from 'lucide-react';
import type { Product } from '@/lib/types';
import { criteria, evaluateEvidence, formatDate } from '@/lib/rating';
import { ingredients } from '@/data/ingredients';
export function Comparison({products,requested}:{products:Product[];requested?:string[]}){
  const now=useEvidenceTime();
  const router=useRouter();
  const {compared,toggleCompare,hydrated,notify}=useCollection();const ids=requested??compared;const selected=ids.map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>!!p).slice(0,3);
  async function copy(){try{await navigator.clipboard.writeText(`${location.origin}${publicPath('/compare/')}?ids=${selected.map(p=>p.id).join(',')}`);notify('Comparison link copied');}catch{notify('Copy the comparison URL from your address bar.');}}
  function remove(id:string){if(compared.includes(id))toggleCompare(id);if(requested!==undefined){const remaining=selected.filter(p=>p.id!==id).map(p=>p.id);router.replace(`/compare?ids=${remaining.join(',')}`);}}
  function exportComparison(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),methodology:`${location.origin}${publicPath('/methodology/')}`,notice:'Evidence coverage measures available documentation, not safety or clinical benefit.',products:selected.map(product=>({product,rating:evaluateEvidence(product.evidence)}))},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='neurotrino-comparison.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(requested===undefined&&!hydrated)return <p className="section-intro">Loading your comparison…</p>;
  if(!selected.length)return <div className="empty-state"><Layers3 size={34}/><h2>Put the evidence side by side.</h2><p>Select up to three products to see what is documented, and what is still unknown.</p><Link className="button" href="/products">Explore products <ArrowRight size={17}/></Link></div>;
  const mixed=new Set(selected.map(p=>p.ingredient_slug)).size>1;
  return <><div className="compare-toolbar"><p>{selected.length} of 3 products {selected.length===1?'· Add another product to compare.':''}</p><div className="comparison-actions"><button className="text-button" onClick={exportComparison}>Export comparison ↓</button><button className="text-button" onClick={copy}>Copy comparison link ↗</button></div></div>{mixed&&<div className="honesty-note"><p>These products contain different supplements. Their evidence coverage is comparable; their effects, doses, and suitability are not interchangeable.</p></div>}<div className="table-scroll comparison-table"><table><caption>Product evidence comparison</caption><thead><tr><th>What we know</th>{selected.map(p=><th key={p.id}><span className="product-brand">{p.brand}</span><Link href={`/products/${p.slug}`}>{p.name} ↗</Link><small>{ingredients.find(i=>i.slug===p.ingredient_slug)?.name}</small></th>)}</tr></thead><tbody><tr><th>Natural Product Number</th>{selected.map(p=><td key={p.id}>{p.npn}</td>)}</tr><tr><th>Form</th>{selected.map(p=><td key={p.id}>{p.form}</td>)}</tr><tr><th>Evidence coverage <small>Not a safety score</small></th>{selected.map(p=>{const r=evaluateEvidence(p.evidence,now);return <td key={p.id}><strong className="table-score">{r.score===null?'Withheld':`${r.score}/100`}</strong><small>{r.label}</small></td>;})}</tr>{criteria.map(c=><tr key={c.kind}><th>{c.title}</th>{selected.map(p=>{const row=evaluateEvidence(p.evidence,now).rows.find(r=>r.kind===c.kind)!;return <td key={p.id}><span className={`status-label status-${row.status}`}>{row.status==='verified'?'Documented':row.status==='concern'?'Unresolved concern':row.status==='stale'?'Refresh needed':'Not verified'}</span>{row.record&&<><small>Checked {formatDate(row.record.checked_at)}</small><a className="source-link" href={row.record.source_url} target="_blank" rel="noopener noreferrer">Source ↗</a></>}</td>;})}</tr>)}<tr><th>Last licence retrieval</th>{selected.map(p=><td key={p.id}>{formatDate(p.checked_at)}</td>)}</tr><tr><th>Read the full record</th>{selected.map(p=><td key={p.id}><Link className="text-link" href={`/products/${p.slug}`}>Product details →</Link>{<button className="text-button" onClick={()=>remove(p.id)} aria-label={`Remove ${p.name} from comparison`}><X size={14}/>Remove</button>}</td>)}</tr></tbody></table></div><p className="meta-text">This is a comparison of documentation. No reviewed testing or recall evidence means unknown, not passed. Licence age and company age are different facts.</p></>;
}
