'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { LogOut, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import type { EvidenceKind, Product } from '@/lib/types';
import type { BrandHistory } from '@/lib/db';
import { criteria, formatDate } from '@/lib/rating';
import { ingredients } from '@/data/ingredients';
export function EditorLogin(){
  const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');try{const response=await fetch('/api/review/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:form.get('token')})});const result=await response.json();if(!response.ok)throw new Error(result.error);router.refresh();}catch(error){setError(error instanceof Error?error.message:'Sign-in failed');}finally{setBusy(false);}}
  return <div className="login-card"><ShieldCheck size={29}/><h2>The editorial desk.</h2><p>Sign in to review evidence, refresh official records, and add source-backed assessments.</p><form className="editor-form" onSubmit={submit}><label>Editor key<input required type="password" name="token" autoComplete="current-password" placeholder="Your private editor key"/></label>{error&&<p className="form-message error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?'Signing in…':'Open editorial desk'}</button><p className="form-help">For a local installation, the project’s README explains how to retrieve the editor key. Public visitors cannot modify evidence.</p></form></div>;
}
async function post(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||data.message||'Request failed');return data;}
export function ReviewDesk({products,brands}:{products:Product[];brands:BrandHistory[]}){
  const router=useRouter();const [npn,setNpn]=useState(products[0]?.npn||'');const [kind,setKind]=useState<EvidenceKind>('testing');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const product=products.find(p=>p.npn===npn);const record=product?.evidence.find(e=>e.kind===kind);const brand=brands.find(b=>b.id===product?.brand_id);
  async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');setError('');try{await fn();setMessage(success);router.refresh();}catch(error){setError(error instanceof Error?error.message:'Action failed');}finally{setBusy(false);}}
  return <><div className="editor-top"><div className="page-heading"><span className="eyebrow">PRIVATE EDITORIAL WORKSPACE</span><h1>Keep the record <em>honest.</em></h1><p>Every saved check updates the public evidence profile and creates an audit entry.</p></div><button className="text-button" onClick={()=>action(()=>post('/api/review/logout',{}),'Signed out')}><LogOut size={15}/>Sign out</button></div>
    {message&&<div className="honesty-note" role="status"><p>{message}</p></div>}{error&&<div className="honesty-note" role="alert"><p className="form-message error">{error}</p></div>}
    <div className="editor-grid"><section className="editor-panel"><h2>Review a product.</h2><div className="editor-form"><label>Product<select aria-label="Editorial product" value={npn} onChange={e=>setNpn(e.target.value)}>{products.map(p=><option value={p.npn} key={p.npn}>{p.brand} · {p.name} · {p.npn}</option>)}</select></label><label>Evidence check<select aria-label="Evidence check" value={kind} onChange={e=>setKind(e.target.value as EvidenceKind)}>{criteria.map(c=><option key={c.kind} value={c.kind}>{c.title}</option>)}</select></label></div>
    {product&&<><div className="record-preview" style={{margin:'18px 0'}}><strong>NPN {product.npn} · {product.licence_status}</strong><p>Licence holder: {product.licence_holder}</p><p>Retrieved {formatDate(product.checked_at)} · Selected check revision {record?.revision??0}</p><a className="source-link" href={`https://health-products.canada.ca/lnhpd-bdpsnh/info?licence=${product.npn}`} target="_blank" rel="noopener noreferrer">Open official licence ↗</a></div><div className="editor-actions"><button disabled={busy} className="button secondary small" onClick={()=>action(()=>post('/api/review/refresh',{npn}),'Official licence refreshed. Other checks are unchanged.')}><RefreshCw size={14}/>{busy?'Working…':'Refresh licence'}</button></div>
    <form key={`${npn}-${kind}-${record?.revision??0}`} className="editor-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void action(()=>post(`/api/review/evidence/${npn}`,{kind,verdict:data.get('verdict'),summary:data.get('summary'),source_url:data.get('source_url'),source_title:data.get('source_title'),publisher:data.get('publisher'),scope:data.get('scope'),checked_at:new Date(`${data.get('checked_at')}T00:00:00Z`).toISOString(),revision:record?.revision??0,attested:data.get('attested')==='on'}),'Evidence review saved and recorded in the audit history.');}}>
      <div className="field-row"><label>Assessment<select name="verdict" defaultValue={record?.verdict||'unknown'}><option value="unknown">Not verified / insufficient evidence</option><option value="verified">Documented and verified</option><option value="concern">Unresolved concern</option></select></label><label>Reviewed on<input name="checked_at" required type="date" max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)}/></label></div>
      <label>What did you establish?<textarea name="summary" minLength={30} maxLength={2500} required defaultValue={record?.summary||''} placeholder="Describe the finding, uncertainty, and whether a concern is current, historical, resolved, or an allegation."/></label>
      <label>Source URL<input name="source_url" type="url" required defaultValue={record?.source_url||''} placeholder="https://…"/></label><div className="field-row"><label>Source title<input name="source_title" required minLength={5} defaultValue={record?.source_title||''}/></label><label>Publisher<input name="publisher" required minLength={2} defaultValue={record?.publisher||''}/></label></div>
      <label>Exact product, market, batch, and review scope<textarea name="scope" minLength={15} maxLength={1000} required defaultValue={record?.scope||''} placeholder="Include the NPN, Canadian formulation, covered lot(s), search period, and any facility-to-product relationship."/></label><label className="check-label"><input type="checkbox" name="attested" required/>I reviewed this source and checked its identity, market, scope, and dates. I have not treated missing evidence as a pass.</label><button disabled={busy} className="button"><Save size={16}/>{busy?'Saving…':'Publish evidence review'}</button>
    </form></>}
    </section><div><section className="editor-panel"><h2>Add an official record.</h2><p>Import by NPN. The licence holder becomes the initial display brand. No independent testing or clean-history claim is created.</p><form className="editor-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void action(()=>post('/api/review/import',{npn:data.get('npn'),ingredient:data.get('ingredient'),attested:data.get('attested')==='on'}),'Official product record imported. Review its brand identity and remaining evidence.');}}><label>Natural Product Number<input name="npn" required inputMode="numeric" pattern="[0-9]{8}" maxLength={8} placeholder="8 digits"/></label><label>Supplement guide<select name="ingredient">{ingredients.filter(item => item.kind !== 'research').map(i=><option value={i.slug} key={i.slug}>{i.name}</option>)}</select></label><label className="check-label"><input name="attested" type="checkbox" required/>I checked that this licence belongs in the selected ingredient guide.</label><button className="button secondary" disabled={busy}>Import Health Canada record</button></form></section>
    {brand&&<section className="editor-panel" style={{marginTop:25}}><h2>Brand history.</h2><p>{brand.name}. Record history separately from product quality. Company age never increases the evidence score.</p><form className="editor-form" key={brand.id} onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void action(()=>post(`/api/review/brand/${brand.id}`,{year:data.get('year')?Number(data.get('year')):null,source:data.get('source'),note:data.get('note')}),'Brand history saved with its source.');}}><label>Founded year (leave blank if uncertain)<input name="year" type="number" min={1600} max={new Date().getUTCFullYear()} defaultValue={brand.founded_year??''}/></label><label>History source URL<input required type="url" name="source" defaultValue={brand.history_source??''}/></label><label>Context and ownership changes<textarea required minLength={30} name="note" defaultValue={brand.history_note??''}/></label><button className="button secondary" disabled={busy}>Save brand history</button></form></section>}
    <section className="editor-panel" style={{marginTop:25}}><h2>Before publishing.</h2><p>For testing, use the certifier’s record and match the Canadian product. For manufacturing, establish the facility relationship. For recalls, record the searches, covered period, exact affected products, and whether issues remain unresolved.</p><p>Do not enter company marketing language as independently verified evidence. Keep complaints and allegations distinct from established findings.</p></section></div></div>
  </>;
}
