import { SourceStatus } from '@/components/source-status';
import { getProducts, getSyncRuns } from '@/lib/db';
import { formatDate } from '@/lib/rating';
import { ArrowUpRight } from 'lucide-react';
export const metadata={title:'Sources and updates'};
const sources=[
  ['Health Canada: Licensed Natural Health Products Database','Imported by exact NPN. Licence records, medicinal ingredients, purpose text, and available warnings.','https://health-products.canada.ca/lnhpd-bdpsnh/'],
  ['Health Canada: natural health product inspections','Reference source for editorial review. Not yet automatically matched to the products in this collection.','https://www.drug-inspections.canada.ca/nhp/index-en.html'],
  ['Government of Canada: recalls and safety alerts','Official recall lookup. Recall clearance requires an explicit review; licence imports do not assert a clean recall history.','https://recalls-rappels.canada.ca/en'],
  ['NSF: certified dietary supplements','Reference directory for verifying product-specific certifications. No brand-wide certification assumptions.','https://info.nsf.org/certified/dietary/'],
  ['NSF Certified for Sport: product directory','Includes market and lot details. The exact product and certification scope must be reviewed.','https://nsfsport-prod.nsf.org/certified-products/'],
  ['NIH Office of Dietary Supplements','Consumer fact sheets underpin the nutrient field notes; they do not endorse our selected products.','https://ods.od.nih.gov/factsheets/list-all/'],
  ['NIH National Center for Complementary and Integrative Health','Context for melatonin’s uses, uncertainties, and safety.','https://www.nccih.nih.gov/health/melatonin-what-you-need-to-know'],
];
export default async function Sources(){const products=await getProducts();const runs=await getSyncRuns();return <main id="main" className="wrap prose-page"><div className="page-heading"><span className="eyebrow">EVERY DISCOVERY HAS A TRAIL</span><h1>Back to <em>the source.</em></h1><p>The catalogue starts with official Canadian licence records. Other checks need their own research. Here is what is connected, what has been retrieved, and what remains unverified.</p></div><SourceStatus products={products}/><section className="prose-block"><h2>Source directory.</h2>{sources.map(([title,description,url])=><a className="source-row" key={url} href={url} target="_blank" rel="noopener noreferrer"><span><strong>{title}</strong><small>{description}</small></span><ArrowUpRight size={18}/></a>)}</section><section className="prose-block"><h2>Retrieval history.</h2>{process.env.NEXT_PUBLIC_STATIC_EDITION==='true'&&<p>This public edition uses checked-in source records. Updates appear after editorial source changes are published; this site does not run a live refresh job.</p>}<p>“Last retrieved” records when this app successfully fetched data. It does not mean the upstream authority updated the record on that day. The initial catalogue is a dated snapshot; scheduled refreshes require an operator to configure the provided refresh job.</p>{runs.length?runs.map(run=><div className="sync-state" key={run.id}><strong>{run.status}</strong> · {formatDate(run.started_at)} · {run.succeeded} updated, {run.failed} failed<p>{run.message}</p></div>):<div className="sync-state">Initial sourced catalogue loaded. No subsequent refresh job has completed on this installation.</div>}<p>Where data could not be matched or verified, the interface preserves the unknown state. It never fills missing testing or recall results with a passing mark.</p></section></main>;}
